name: applying_pressure
description: Flutter Applying Pressure app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera:
  path_provider:
  path:
  cupertino_icons: ^1.0.2
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  flutter_masked_text2: ^0.9.1
  firebase_auth: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
