// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4aLvwOXoSzblHgq2azgFd1b840p1IuY0',
    appId: '1:65700282049:web:053ee5b689f73bc5915e40',
    messagingSenderId: '65700282049',
    projectId: 'applyingpressure-a0205',
    authDomain: 'applyingpressure-a0205.firebaseapp.com',
    storageBucket: 'applyingpressure-a0205.appspot.com',
    measurementId: 'G-FS1LQ5NQDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN3C-Y7z7v_xJfTp8CVwxuQvTjtYYbtq8',
    appId: '1:65700282049:android:43744ac8d4df454a915e40',
    messagingSenderId: '65700282049',
    projectId: 'applyingpressure-a0205',
    storageBucket: 'applyingpressure-a0205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpqf1y4FMVb91PLOo0UiHUTa6v528JREc',
    appId: '1:65700282049:ios:83466a551aff7bd0915e40',
    messagingSenderId: '65700282049',
    projectId: 'applyingpressure-a0205',
    storageBucket: 'applyingpressure-a0205.appspot.com',
    iosClientId: '65700282049-5h5kl8gvem22r7utk6tirhlf0qt107kf.apps.googleusercontent.com',
    iosBundleId: 'com.garrytech.applyingPressure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpqf1y4FMVb91PLOo0UiHUTa6v528JREc',
    appId: '1:65700282049:ios:83466a551aff7bd0915e40',
    messagingSenderId: '65700282049',
    projectId: 'applyingpressure-a0205',
    storageBucket: 'applyingpressure-a0205.appspot.com',
    iosClientId: '65700282049-5h5kl8gvem22r7utk6tirhlf0qt107kf.apps.googleusercontent.com',
    iosBundleId: 'com.garrytech.applyingPressure',
  );
}
